version: '3.9'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=my_database
      - POSTGRES_USER=movieapi
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql